In [1]:
import pandas as pd
import numpy as np

In [3]:
tracts =pd.read_csv('ACSDT5Y2018.B02001_data_with_overlays_2020-04-19T221609.csv', skiprows=[0])
tracts.head(3)

,id,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,Estimate!!Total!!White alone,Margin of Error!!Total!!White alone,Estimate!!Total!!Black or African American alone,Margin of Error!!Total!!Black or African American alone,Estimate!!Total!!American Indian and Alaska Native alone,Margin of Error!!Total!!American Indian and Alaska Native alone,...,Estimate!!Total!!Native Hawaiian and Other Pacific Islander alone,Margin of Error!!Total!!Native Hawaiian and Other Pacific Islander alone,Estimate!!Total!!Some other race alone,Margin of Error!!Total!!Some other race alone,Estimate!!Total!!Two or more races,Margin of Error!!Total!!Two or more races,Estimate!!Total!!Two or more races!!Two races including Some other race,Margin of Error!!Total!!Two or more races!!Two races including Some other race,"Estimate!!Total!!Two or more races!!Two races excluding Some other race, and three or more races","Margin of Error!!Total!!Two or more races!!Two races excluding Some other race, and three or more races"
0,1400000US36005042902,"Census Tract 429.02, Bronx County, New York",4205,387,485,173,1387,332,179,144,...,0,12,1839,508,117,119,12,19,105,119
1,1400000US36005033000,"Census Tract 330, Bronx County, New York",5885,693,2941,828,897,366,0,17,...,0,17,2047,834,0,17,0,17,0,17
2,1400000US36005035800,"Census Tract 358, Bronx County, New York",8054,787,779,398,5958,808,0,17,...,0,17,883,605,254,199,237,195,17,27

In [4]:
tracts = tracts.join(pd.DataFrame(tracts['Geographic Area Name'].str.split(',').tolist(),
                                   columns = ['tract','county','city']))
tracts['tract'] = tracts['tract'].apply(lambda x : x[13:])
tracts.head(3)

,id,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,Estimate!!Total!!White alone,Margin of Error!!Total!!White alone,Estimate!!Total!!Black or African American alone,Margin of Error!!Total!!Black or African American alone,Estimate!!Total!!American Indian and Alaska Native alone,Margin of Error!!Total!!American Indian and Alaska Native alone,...,Margin of Error!!Total!!Some other race alone,Estimate!!Total!!Two or more races,Margin of Error!!Total!!Two or more races,Estimate!!Total!!Two or more races!!Two races including Some other race,Margin of Error!!Total!!Two or more races!!Two races including Some other race,"Estimate!!Total!!Two or more races!!Two races excluding Some other race, and three or more races","Margin of Error!!Total!!Two or more races!!Two races excluding Some other race, and three or more races",tract,county,city
0,1400000US36005042902,"Census Tract 429.02, Bronx County, New York",4205,387,485,173,1387,332,179,144,...,508,117,119,12,19,105,119,429.02,Bronx County,New York
1,1400000US36005033000,"Census Tract 330, Bronx County, New York",5885,693,2941,828,897,366,0,17,...,834,0,17,0,17,0,17,330,Bronx County,New York
2,1400000US36005035800,"Census Tract 358, Bronx County, New York",8054,787,779,398,5958,808,0,17,...,605,254,199,237,195,17,27,358,Bronx County,New York

In [8]:
cols_to_keep = ['city', 'tract', 'county', 'Total', 'White', 'Black', 'Native', 'Asian', 
                'Pacific Islander', 'Other','Two or More']

prettier_cols = {
    'Estimate!!Total': 'Total',
    'Estimate!!Total!!White alone' : 'White',
     'Estimate!!Total!!Black or African American alone': 'Black',
     'Estimate!!Total!!American Indian and Alaska Native alone': 'Native',
     'Estimate!!Total!!Asian alone': 'Asian',
     'Estimate!!Total!!Native Hawaiian and Other Pacific Islander alone': 'Pacific Islander',
     'Estimate!!Total!!Some other race alone': 'Other',
     'Estimate!!Total!!Two or more races': 'Two or More'
}

list(tracts.columns)

['id',
 'Geographic Area Name',
 'Total',
 'Margin of Error!!Total',
 'White',
 'Margin of Error!!Total!!White alone',
 'Black',
 'Margin of Error!!Total!!Black or African American alone',
 'Native',
 'Margin of Error!!Total!!American Indian and Alaska Native alone',
 'Asian',
 'Margin of Error!!Total!!Asian alone',
 'Pacific Islander',
 'Margin of Error!!Total!!Native Hawaiian and Other Pacific Islander alone',
 'Other',
 'Margin of Error!!Total!!Some other race alone',
 'Two or More',
 'Margin of Error!!Total!!Two or more races',
 'Estimate!!Total!!Two or more races!!Two races including Some other race',
 'Margin of Error!!Total!!Two or more races!!Two races including Some other race',
 'Estimate!!Total!!Two or more races!!Two races excluding Some other race, and three or more races',
 'Margin of Error!!Total!!Two or more races!!Two races excluding Some other race, and three or more races',
 'tract',
 'county',
 'city']

In [7]:
tracts.rename(columns=prettier_cols, inplace=True)
tracts.head()

,id,Geographic Area Name,Total,Margin of Error!!Total,White,Margin of Error!!Total!!White alone,Black,Margin of Error!!Total!!Black or African American alone,Native,Margin of Error!!Total!!American Indian and Alaska Native alone,...,Margin of Error!!Total!!Some other race alone,Two or More,Margin of Error!!Total!!Two or more races,Estimate!!Total!!Two or more races!!Two races including Some other race,Margin of Error!!Total!!Two or more races!!Two races including Some other race,"Estimate!!Total!!Two or more races!!Two races excluding Some other race, and three or more races","Margin of Error!!Total!!Two or more races!!Two races excluding Some other race, and three or more races",tract,county,city
0,1400000US36005042902,"Census Tract 429.02, Bronx County, New York",4205,387,485,173,1387,332,179,144,...,508,117,119,12,19,105,119,429.02,Bronx County,New York
1,1400000US36005033000,"Census Tract 330, Bronx County, New York",5885,693,2941,828,897,366,0,17,...,834,0,17,0,17,0,17,330,Bronx County,New York
2,1400000US36005035800,"Census Tract 358, Bronx County, New York",8054,787,779,398,5958,808,0,17,...,605,254,199,237,195,17,27,358,Bronx County,New York
3,1400000US36005037100,"Census Tract 371, Bronx County, New York",4322,478,1122,433,1474,353,13,20,...,477,232,149,127,119,105,104,371,Bronx County,New York
4,1400000US36005038500,"Census Tract 385, Bronx County, New York",4757,531,344,234,1521,347,35,38,...,471,188,116,130,95,58,64,385,Bronx County,New York

In [9]:
for_export = tracts[cols_to_keep]
for_export

,city,tract,county,Total,White,Black,Native,Asian,Pacific Islander,Other,Two or More
0,New York,429.02,Bronx County,4205,485,1387,179,198,0,1839,117
1,New York,330,Bronx County,5885,2941,897,0,0,0,2047,0
2,New York,358,Bronx County,8054,779,5958,0,180,0,883,254
3,New York,371,Bronx County,4322,1122,1474,13,18,0,1463,232
4,New York,385,Bronx County,4757,344,1521,35,0,0,2669,188
...,...,...,...,...,...,...,...,...,...,...,...
2162,New York,170.12,Richmond County,4444,4136,17,0,172,16,52,51
2163,New York,244.02,Richmond County,4654,4431,33,0,179,0,11,0
2164,New York,277.05,Richmond County,5843,4139,156,0,1238,0,54,256
2165,New York,277.06,Richmond County,3520,2197,432,0,679,0,130,82
2166,New York,9901,Richmond County,0,0,0,0,0,0,0,0

In [10]:
for_export.to_csv('tract_race_acs2018.csv',index=False)