In [1]:
import pandas as pd
import numpy as np

In [27]:
tracts =pd.read_csv('ACSST5Y2018.S1901_data_with_overlays_2020-04-19T193840.csv', skiprows=[0])
tracts.head(3)

,id,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households MOE!!Total,Estimate!!Families!!Total,Margin of Error!!Families MOE!!Total,Estimate!!Married-couple families!!Total,Margin of Error!!Married-couple families MOE!!Total,Estimate!!Nonfamily households!!Total,Margin of Error!!Nonfamily households MOE!!Total,...,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Margin of Error!!Nonfamily households MOE!!PERCENT ALLOCATED!!Family income in the past 12 months,Estimate!!Households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Households MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Estimate!!Families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Families MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Estimate!!Married-couple families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Married-couple families MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
0,1400000US36005000100,"Census Tract 1, Bronx County, New York",0,17,0,17,0,17,0,17,...,(X),(X),(X),(X),(X),(X),(X),(X),-,(X)
1,1400000US36005000200,"Census Tract 2, Bronx County, New York",1328,84,958,131,527,117,370,110,...,(X),(X),(X),(X),(X),(X),(X),(X),21.9,(X)
2,1400000US36005000400,"Census Tract 4, Bronx County, New York",1963,96,1419,165,683,150,544,154,...,(X),(X),(X),(X),(X),(X),(X),(X),21.9,(X)

In [28]:
tracts = tracts.join(pd.DataFrame(tracts['Geographic Area Name'].str.split(',').tolist(),
                                   columns = ['tract','county','city']))
tracts['tract'] = tracts['tract'].apply(lambda x : x[13:])
tracts.head(3)

,id,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households MOE!!Total,Estimate!!Families!!Total,Margin of Error!!Families MOE!!Total,Estimate!!Married-couple families!!Total,Margin of Error!!Married-couple families MOE!!Total,Estimate!!Nonfamily households!!Total,Margin of Error!!Nonfamily households MOE!!Total,...,Margin of Error!!Households MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Estimate!!Families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Families MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Estimate!!Married-couple families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Married-couple families MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,tract,county,city
0,1400000US36005000100,"Census Tract 1, Bronx County, New York",0,17,0,17,0,17,0,17,...,(X),(X),(X),(X),(X),-,(X),1,Bronx County,New York
1,1400000US36005000200,"Census Tract 2, Bronx County, New York",1328,84,958,131,527,117,370,110,...,(X),(X),(X),(X),(X),21.9,(X),2,Bronx County,New York
2,1400000US36005000400,"Census Tract 4, Bronx County, New York",1963,96,1419,165,683,150,544,154,...,(X),(X),(X),(X),(X),21.9,(X),4,Bronx County,New York

In [40]:
cols_to_keep = ['city', 'tract', 'county', 'Households (HH) Count', 'HH 0-10k', 'HH 10k-15k', 'HH 15k-25k', 
                'HH 25k-35k', 'HH 35k-50k', 'HH 50k-75k', 'HH 75k-100k', 'HH 100k-150k', 'HH 150k-200k', 'HH 200k-UP', 
                'Household Median Income', 'Household Mean Income']

prettier_cols = {
    'Estimate!!Households!!Total': 'Households (HH) Count',
    'Estimate!!Households!!Total!!Less than $10,000' : 'HH 0-10k',
    'Estimate!!Households!!Total!!$10,000 to $14,999': 'HH 10k-15k',
    'Estimate!!Households!!Total!!$15,000 to $24,999': 'HH 15k-25k',
    'Estimate!!Households!!Total!!$25,000 to $34,999': 'HH 25k-35k',
    'Estimate!!Households!!Total!!$35,000 to $49,999': 'HH 35k-50k',
    'Estimate!!Households!!Total!!$50,000 to $74,999': 'HH 50k-75k',
    'Estimate!!Households!!Total!!$75,000 to $99,999': 'HH 75k-100k',
    'Estimate!!Households!!Total!!$100,000 to $149,999': 'HH 100k-150k',
    'Estimate!!Households!!Total!!$150,000 to $199,999': 'HH 150k-200k',
    'Estimate!!Households!!Total!!$200,000 or more': 'HH 200k-UP',
    'Estimate!!Households!!Median income (dollars)': 'Household Median Income',
    'Estimate!!Households!!Mean income (dollars)': 'Household Mean Income',
}

list(tracts.columns)

['id',
 'Geographic Area Name',
 'Households (HH) Count',
 'Margin of Error!!Households MOE!!Total',
 'Estimate!!Families!!Total',
 'Margin of Error!!Families MOE!!Total',
 'Estimate!!Married-couple families!!Total',
 'Margin of Error!!Married-couple families MOE!!Total',
 'Estimate!!Nonfamily households!!Total',
 'Margin of Error!!Nonfamily households MOE!!Total',
 'HH 0-10k',
 'Margin of Error!!Households MOE!!Total!!Less than $10,000',
 'Estimate!!Families!!Total!!Less than $10,000',
 'Margin of Error!!Families MOE!!Total!!Less than $10,000',
 'Estimate!!Married-couple families!!Total!!Less than $10,000',
 'Margin of Error!!Married-couple families MOE!!Total!!Less than $10,000',
 'Estimate!!Nonfamily households!!Total!!Less than $10,000',
 'Margin of Error!!Nonfamily households MOE!!Total!!Less than $10,000',
 'HH 10k-15k',
 'Margin of Error!!Households MOE!!Total!!$10,000 to $14,999',
 'Estimate!!Families!!Total!!$10,000 to $14,999',
 'Margin of Error!!Families MOE!!Total!!$10,000 to $14,999',
 'Estimate!!Married-couple families!!Total!!$10,000 to $14,999',
 'Margin of Error!!Married-couple families MOE!!Total!!$10,000 to $14,999',
 'Estimate!!Nonfamily households!!Total!!$10,000 to $14,999',
 'Margin of Error!!Nonfamily households MOE!!Total!!$10,000 to $14,999',
 'HH 15k-25k',
 'Margin of Error!!Households MOE!!Total!!$15,000 to $24,999',
 'Estimate!!Families!!Total!!$15,000 to $24,999',
 'Margin of Error!!Families MOE!!Total!!$15,000 to $24,999',
 'Estimate!!Married-couple families!!Total!!$15,000 to $24,999',
 'Margin of Error!!Married-couple families MOE!!Total!!$15,000 to $24,999',
 'Estimate!!Nonfamily households!!Total!!$15,000 to $24,999',
 'Margin of Error!!Nonfamily households MOE!!Total!!$15,000 to $24,999',
 'HH 25k-35k',
 'Margin of Error!!Households MOE!!Total!!$25,000 to $34,999',
 'Estimate!!Families!!Total!!$25,000 to $34,999',
 'Margin of Error!!Families MOE!!Total!!$25,000 to $34,999',
 'Estimate!!Married-couple families!!Total!!$25,000 to $34,999',
 'Margin of Error!!Married-couple families MOE!!Total!!$25,000 to $34,999',
 'Estimate!!Nonfamily households!!Total!!$25,000 to $34,999',
 'Margin of Error!!Nonfamily households MOE!!Total!!$25,000 to $34,999',
 'HH 35k-50k',
 'Margin of Error!!Households MOE!!Total!!$35,000 to $49,999',
 'Estimate!!Families!!Total!!$35,000 to $49,999',
 'Margin of Error!!Families MOE!!Total!!$35,000 to $49,999',
 'Estimate!!Married-couple families!!Total!!$35,000 to $49,999',
 'Margin of Error!!Married-couple families MOE!!Total!!$35,000 to $49,999',
 'Estimate!!Nonfamily households!!Total!!$35,000 to $49,999',
 'Margin of Error!!Nonfamily households MOE!!Total!!$35,000 to $49,999',
 'HH 50k-75k',
 'Margin of Error!!Households MOE!!Total!!$50,000 to $74,999',
 'Estimate!!Families!!Total!!$50,000 to $74,999',
 'Margin of Error!!Families MOE!!Total!!$50,000 to $74,999',
 'Estimate!!Married-couple families!!Total!!$50,000 to $74,999',
 'Margin of Error!!Married-couple families MOE!!Total!!$50,000 to $74,999',
 'Estimate!!Nonfamily households!!Total!!$50,000 to $74,999',
 'Margin of Error!!Nonfamily households MOE!!Total!!$50,000 to $74,999',
 'HH 75k-100k',
 'Margin of Error!!Households MOE!!Total!!$75,000 to $99,999',
 'Estimate!!Families!!Total!!$75,000 to $99,999',
 'Margin of Error!!Families MOE!!Total!!$75,000 to $99,999',
 'Estimate!!Married-couple families!!Total!!$75,000 to $99,999',
 'Margin of Error!!Married-couple families MOE!!Total!!$75,000 to $99,999',
 'Estimate!!Nonfamily households!!Total!!$75,000 to $99,999',
 'Margin of Error!!Nonfamily households MOE!!Total!!$75,000 to $99,999',
 'HH 100k-150k',
 'Margin of Error!!Households MOE!!Total!!$100,000 to $149,999',
 'Estimate!!Families!!Total!!$100,000 to $149,999',
 'Margin of Error!!Families MOE!!Total!!$100,000 to $149,999',
 'Estimate!!Married-couple families!!Total!!$100,000 to $149,999',
 'Margin of Error!!Married-couple families MOE!!Total!!$100,000 to $149,999',
 'Estimate!!Nonfamily households!!Total!!$100,000 to $149,999',
 'Margin of Error!!Nonfamily households MOE!!Total!!$100,000 to $149,999',
 'HH 150k-200k',
 'Margin of Error!!Households MOE!!Total!!$150,000 to $199,999',
 'Estimate!!Families!!Total!!$150,000 to $199,999',
 'Margin of Error!!Families MOE!!Total!!$150,000 to $199,999',
 'Estimate!!Married-couple families!!Total!!$150,000 to $199,999',
 'Margin of Error!!Married-couple families MOE!!Total!!$150,000 to $199,999',
 'Estimate!!Nonfamily households!!Total!!$150,000 to $199,999',
 'Margin of Error!!Nonfamily households MOE!!Total!!$150,000 to $199,999',
 'HH 200k-UP',
 'Margin of Error!!Households MOE!!Total!!$200,000 or more',
 'Estimate!!Families!!Total!!$200,000 or more',
 'Margin of Error!!Families MOE!!Total!!$200,000 or more',
 'Estimate!!Married-couple families!!Total!!$200,000 or more',
 'Margin of Error!!Married-couple families MOE!!Total!!$200,000 or more',
 'Estimate!!Nonfamily households!!Total!!$200,000 or more',
 'Margin of Error!!Nonfamily households MOE!!Total!!$200,000 or more',
 'Household Median Income',
 'Margin of Error!!Households MOE!!Median income (dollars)',
 'Estimate!!Families!!Median income (dollars)',
 'Margin of Error!!Families MOE!!Median income (dollars)',
 'Estimate!!Married-couple families!!Median income (dollars)',
 'Margin of Error!!Married-couple families MOE!!Median income (dollars)',
 'Estimate!!Nonfamily households!!Median income (dollars)',
 'Margin of Error!!Nonfamily households MOE!!Median income (dollars)',
 'Household Mean Income',
 'Margin of Error!!Households MOE!!Mean income (dollars)',
 'Estimate!!Families!!Mean income (dollars)',
 'Margin of Error!!Families MOE!!Mean income (dollars)',
 'Estimate!!Married-couple families!!Mean income (dollars)',
 'Margin of Error!!Married-couple families MOE!!Mean income (dollars)',
 'Estimate!!Nonfamily households!!Mean income (dollars)',
 'Margin of Error!!Nonfamily households MOE!!Mean income (dollars)',
 'Estimate!!Households!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Margin of Error!!Households MOE!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Estimate!!Families!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Margin of Error!!Families MOE!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Estimate!!Married-couple families!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Margin of Error!!Married-couple families MOE!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Margin of Error!!Nonfamily households MOE!!PERCENT ALLOCATED!!Household income in the past 12 months',
 'Estimate!!Households!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Margin of Error!!Households MOE!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Estimate!!Families!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Margin of Error!!Families MOE!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Estimate!!Married-couple families!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Margin of Error!!Married-couple families MOE!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Margin of Error!!Nonfamily households MOE!!PERCENT ALLOCATED!!Family income in the past 12 months',
 'Estimate!!Households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Margin of Error!!Households MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Estimate!!Families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Margin of Error!!Families MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Estimate!!Married-couple families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Margin of Error!!Married-couple families MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'Margin of Error!!Nonfamily households MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months',
 'tract',
 'county',
 'city']

In [38]:
tracts.rename(columns=prettier_cols, inplace=True)
tracts.head()

,id,Geographic Area Name,Households (HH) Count,Margin of Error!!Households MOE!!Total,Estimate!!Families!!Total,Margin of Error!!Families MOE!!Total,Estimate!!Married-couple families!!Total,Margin of Error!!Married-couple families MOE!!Total,Estimate!!Nonfamily households!!Total,Margin of Error!!Nonfamily households MOE!!Total,...,Margin of Error!!Households MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Estimate!!Families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Families MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Estimate!!Married-couple families!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Married-couple families MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households MOE!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,tract,county,city
0,1400000US36005000100,"Census Tract 1, Bronx County, New York",0,17,0,17,0,17,0,17,...,(X),(X),(X),(X),(X),-,(X),1,Bronx County,New York
1,1400000US36005000200,"Census Tract 2, Bronx County, New York",1328,84,958,131,527,117,370,110,...,(X),(X),(X),(X),(X),21.9,(X),2,Bronx County,New York
2,1400000US36005000400,"Census Tract 4, Bronx County, New York",1963,96,1419,165,683,150,544,154,...,(X),(X),(X),(X),(X),21.9,(X),4,Bronx County,New York
3,1400000US36005001600,"Census Tract 16, Bronx County, New York",1982,91,1524,129,459,144,458,111,...,(X),(X),(X),(X),(X),26.6,(X),16,Bronx County,New York
4,1400000US36005001900,"Census Tract 19, Bronx County, New York",929,57,490,71,232,64,439,77,...,(X),(X),(X),(X),(X),31.4,(X),19,Bronx County,New York

In [41]:
for_export = tracts[cols_to_keep]
for_export

,city,tract,county,Households (HH) Count,HH 0-10k,HH 10k-15k,HH 15k-25k,HH 25k-35k,HH 35k-50k,HH 50k-75k,HH 75k-100k,HH 100k-150k,HH 150k-200k,HH 200k-UP,Household Median Income,Household Mean Income
0,New York,1,Bronx County,0,-,-,-,-,-,-,-,-,-,-,-,-
1,New York,2,Bronx County,1328,6.9,2.4,12.3,9.9,11.5,20.4,9.5,15.4,5.9,5.9,59914,72979
2,New York,4,Bronx County,1963,7.2,1.9,7.6,3.5,8.5,18.0,17.2,17.3,12.6,6.3,82073,94723
3,New York,16,Bronx County,1982,8.4,12.5,11.8,16.5,15.1,17.8,8.1,7.7,1.2,1.1,35802,59663
4,New York,19,Bronx County,929,13.7,10.3,6.7,7.2,18.2,19.3,12.4,10.7,0.0,1.6,42075,54415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2162,New York,303.02,Richmond County,1964,7.1,2.6,5.0,3.4,6.4,19.8,19.2,22.2,11.7,2.5,79865,88807
2163,New York,319.01,Richmond County,1055,50.1,8.6,3.8,2.8,4.5,12.6,9.5,6.4,0.7,0.9,9939,39713
2164,New York,319.02,Richmond County,1670,28.9,5.1,9.9,4.0,10.4,6.1,5.4,16.6,8.9,4.6,37500,69933
2165,New York,323,Richmond County,440,27.7,0.0,8.4,1.8,4.1,10.0,18.0,9.8,18.9,1.4,71250,86995
2166,New York,9901,Richmond County,0,-,-,-,-,-,-,-,-,-,-,-,-

In [43]:
for_export.to_csv('household_income_acs2018.csv',index=False)